branch-defaults:
  default:
    environment: Transaction-platform-env-1
  main:
    environment: Transaction-platform-env-1
environment-defaults:
  Transaction-platform-env-1:
    branch: null
    repository: null
global:
  application_name: transaction-platform
  default_ec2_keyname: null
  default_platform: Python 3.12 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
